# Welcome to everything secret about this program ğŸ¤

# Previously tested with personalized openAI API Key, but installed .gitignore incorrectly and published Private Key to GitHub (and was immediately deleted)
# Make sure to double check contents of .gitignore before commiting secrets.toml to GitHub ğŸ˜³

I believe we're implementing a connection between Google Gemini, instead of OpenAI, so ideally will only have to connect the api key

How to use Gemini API Key:

https://ai.google.dev/gemini-api/docs/api-key

