# Welcome to everything secret about this program ğŸ¤

# Previously tested with personalized openAI API Key, but installed .gitignore incorrectly and published Private Key to GitHub (and was immediately deleted)
# Make sure to double check contents of .gitignore before commiting secrets.toml to GitHub ğŸ˜³
